services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - /data:/data
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config/prowlarr:/config
    ports:
      - 9696:9696
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config/radarr:/config
      - /data:/data
    ports:
      - 7878:7878
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config/sonarr:/config
      - /data:/data
    ports:
      - 8989:8989
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /opt/arr-stack/config/jackett:/config
    ports:
      - 9117:9117
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Madrid
    ports:
      - 8191:8191
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped

  jdownloader2:
    image: jlesage/jdownloader-2:latest
    container_name: jdownloader2
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config/jdownloader2:/config
      - /data:/data
    ports:
      - 5800:5800
    restart: unless-stopped
